// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: message.proto
#ifndef GRPC_message_2eproto__INCLUDED
#define GRPC_message_2eproto__INCLUDED

#include "message.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace chat_message {

class VerifyService final {
 public:
  static constexpr char const* service_full_name() {
    return "chat_message.VerifyService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetVerifyCode(::grpc::ClientContext* context, const ::chat_message::GetVerifyRequest& request, ::chat_message::GetVerifyResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::GetVerifyResponse>> AsyncGetVerifyCode(::grpc::ClientContext* context, const ::chat_message::GetVerifyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::GetVerifyResponse>>(AsyncGetVerifyCodeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::GetVerifyResponse>> PrepareAsyncGetVerifyCode(::grpc::ClientContext* context, const ::chat_message::GetVerifyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::GetVerifyResponse>>(PrepareAsyncGetVerifyCodeRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetVerifyCode(::grpc::ClientContext* context, const ::chat_message::GetVerifyRequest* request, ::chat_message::GetVerifyResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetVerifyCode(::grpc::ClientContext* context, const ::chat_message::GetVerifyRequest* request, ::chat_message::GetVerifyResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::GetVerifyResponse>* AsyncGetVerifyCodeRaw(::grpc::ClientContext* context, const ::chat_message::GetVerifyRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::GetVerifyResponse>* PrepareAsyncGetVerifyCodeRaw(::grpc::ClientContext* context, const ::chat_message::GetVerifyRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetVerifyCode(::grpc::ClientContext* context, const ::chat_message::GetVerifyRequest& request, ::chat_message::GetVerifyResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat_message::GetVerifyResponse>> AsyncGetVerifyCode(::grpc::ClientContext* context, const ::chat_message::GetVerifyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat_message::GetVerifyResponse>>(AsyncGetVerifyCodeRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat_message::GetVerifyResponse>> PrepareAsyncGetVerifyCode(::grpc::ClientContext* context, const ::chat_message::GetVerifyRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat_message::GetVerifyResponse>>(PrepareAsyncGetVerifyCodeRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetVerifyCode(::grpc::ClientContext* context, const ::chat_message::GetVerifyRequest* request, ::chat_message::GetVerifyResponse* response, std::function<void(::grpc::Status)>) override;
      void GetVerifyCode(::grpc::ClientContext* context, const ::chat_message::GetVerifyRequest* request, ::chat_message::GetVerifyResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::chat_message::GetVerifyResponse>* AsyncGetVerifyCodeRaw(::grpc::ClientContext* context, const ::chat_message::GetVerifyRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chat_message::GetVerifyResponse>* PrepareAsyncGetVerifyCodeRaw(::grpc::ClientContext* context, const ::chat_message::GetVerifyRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetVerifyCode_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetVerifyCode(::grpc::ServerContext* context, const ::chat_message::GetVerifyRequest* request, ::chat_message::GetVerifyResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetVerifyCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetVerifyCode() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetVerifyCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVerifyCode(::grpc::ServerContext* /*context*/, const ::chat_message::GetVerifyRequest* /*request*/, ::chat_message::GetVerifyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetVerifyCode(::grpc::ServerContext* context, ::chat_message::GetVerifyRequest* request, ::grpc::ServerAsyncResponseWriter< ::chat_message::GetVerifyResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetVerifyCode<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetVerifyCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetVerifyCode() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::chat_message::GetVerifyRequest, ::chat_message::GetVerifyResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::chat_message::GetVerifyRequest* request, ::chat_message::GetVerifyResponse* response) { return this->GetVerifyCode(context, request, response); }));}
    void SetMessageAllocatorFor_GetVerifyCode(
        ::grpc::MessageAllocator< ::chat_message::GetVerifyRequest, ::chat_message::GetVerifyResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::chat_message::GetVerifyRequest, ::chat_message::GetVerifyResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetVerifyCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVerifyCode(::grpc::ServerContext* /*context*/, const ::chat_message::GetVerifyRequest* /*request*/, ::chat_message::GetVerifyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetVerifyCode(
      ::grpc::CallbackServerContext* /*context*/, const ::chat_message::GetVerifyRequest* /*request*/, ::chat_message::GetVerifyResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetVerifyCode<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetVerifyCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetVerifyCode() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetVerifyCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVerifyCode(::grpc::ServerContext* /*context*/, const ::chat_message::GetVerifyRequest* /*request*/, ::chat_message::GetVerifyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetVerifyCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetVerifyCode() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetVerifyCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVerifyCode(::grpc::ServerContext* /*context*/, const ::chat_message::GetVerifyRequest* /*request*/, ::chat_message::GetVerifyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetVerifyCode(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetVerifyCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetVerifyCode() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetVerifyCode(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetVerifyCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetVerifyCode(::grpc::ServerContext* /*context*/, const ::chat_message::GetVerifyRequest* /*request*/, ::chat_message::GetVerifyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetVerifyCode(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetVerifyCode : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetVerifyCode() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::chat_message::GetVerifyRequest, ::chat_message::GetVerifyResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::chat_message::GetVerifyRequest, ::chat_message::GetVerifyResponse>* streamer) {
                       return this->StreamedGetVerifyCode(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetVerifyCode() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetVerifyCode(::grpc::ServerContext* /*context*/, const ::chat_message::GetVerifyRequest* /*request*/, ::chat_message::GetVerifyResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetVerifyCode(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::chat_message::GetVerifyRequest,::chat_message::GetVerifyResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetVerifyCode<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetVerifyCode<Service > StreamedService;
};

class StatusService final {
 public:
  static constexpr char const* service_full_name() {
    return "chat_message.StatusService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status GetChatServer(::grpc::ClientContext* context, const ::chat_message::GetChatServerRequest& request, ::chat_message::GetChatServerResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::GetChatServerResponse>> AsyncGetChatServer(::grpc::ClientContext* context, const ::chat_message::GetChatServerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::GetChatServerResponse>>(AsyncGetChatServerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::GetChatServerResponse>> PrepareAsyncGetChatServer(::grpc::ClientContext* context, const ::chat_message::GetChatServerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::GetChatServerResponse>>(PrepareAsyncGetChatServerRaw(context, request, cq));
    }
    virtual ::grpc::Status Login(::grpc::ClientContext* context, const ::chat_message::LoginRequest& request, ::chat_message::LoginResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::LoginResponse>> AsyncLogin(::grpc::ClientContext* context, const ::chat_message::LoginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::LoginResponse>>(AsyncLoginRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::LoginResponse>> PrepareAsyncLogin(::grpc::ClientContext* context, const ::chat_message::LoginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::LoginResponse>>(PrepareAsyncLoginRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void GetChatServer(::grpc::ClientContext* context, const ::chat_message::GetChatServerRequest* request, ::chat_message::GetChatServerResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void GetChatServer(::grpc::ClientContext* context, const ::chat_message::GetChatServerRequest* request, ::chat_message::GetChatServerResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void Login(::grpc::ClientContext* context, const ::chat_message::LoginRequest* request, ::chat_message::LoginResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Login(::grpc::ClientContext* context, const ::chat_message::LoginRequest* request, ::chat_message::LoginResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::GetChatServerResponse>* AsyncGetChatServerRaw(::grpc::ClientContext* context, const ::chat_message::GetChatServerRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::GetChatServerResponse>* PrepareAsyncGetChatServerRaw(::grpc::ClientContext* context, const ::chat_message::GetChatServerRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::LoginResponse>* AsyncLoginRaw(::grpc::ClientContext* context, const ::chat_message::LoginRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::LoginResponse>* PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::chat_message::LoginRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status GetChatServer(::grpc::ClientContext* context, const ::chat_message::GetChatServerRequest& request, ::chat_message::GetChatServerResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat_message::GetChatServerResponse>> AsyncGetChatServer(::grpc::ClientContext* context, const ::chat_message::GetChatServerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat_message::GetChatServerResponse>>(AsyncGetChatServerRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat_message::GetChatServerResponse>> PrepareAsyncGetChatServer(::grpc::ClientContext* context, const ::chat_message::GetChatServerRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat_message::GetChatServerResponse>>(PrepareAsyncGetChatServerRaw(context, request, cq));
    }
    ::grpc::Status Login(::grpc::ClientContext* context, const ::chat_message::LoginRequest& request, ::chat_message::LoginResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat_message::LoginResponse>> AsyncLogin(::grpc::ClientContext* context, const ::chat_message::LoginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat_message::LoginResponse>>(AsyncLoginRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat_message::LoginResponse>> PrepareAsyncLogin(::grpc::ClientContext* context, const ::chat_message::LoginRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat_message::LoginResponse>>(PrepareAsyncLoginRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void GetChatServer(::grpc::ClientContext* context, const ::chat_message::GetChatServerRequest* request, ::chat_message::GetChatServerResponse* response, std::function<void(::grpc::Status)>) override;
      void GetChatServer(::grpc::ClientContext* context, const ::chat_message::GetChatServerRequest* request, ::chat_message::GetChatServerResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void Login(::grpc::ClientContext* context, const ::chat_message::LoginRequest* request, ::chat_message::LoginResponse* response, std::function<void(::grpc::Status)>) override;
      void Login(::grpc::ClientContext* context, const ::chat_message::LoginRequest* request, ::chat_message::LoginResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::chat_message::GetChatServerResponse>* AsyncGetChatServerRaw(::grpc::ClientContext* context, const ::chat_message::GetChatServerRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chat_message::GetChatServerResponse>* PrepareAsyncGetChatServerRaw(::grpc::ClientContext* context, const ::chat_message::GetChatServerRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chat_message::LoginResponse>* AsyncLoginRaw(::grpc::ClientContext* context, const ::chat_message::LoginRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chat_message::LoginResponse>* PrepareAsyncLoginRaw(::grpc::ClientContext* context, const ::chat_message::LoginRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_GetChatServer_;
    const ::grpc::internal::RpcMethod rpcmethod_Login_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status GetChatServer(::grpc::ServerContext* context, const ::chat_message::GetChatServerRequest* request, ::chat_message::GetChatServerResponse* response);
    virtual ::grpc::Status Login(::grpc::ServerContext* context, const ::chat_message::LoginRequest* request, ::chat_message::LoginResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_GetChatServer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_GetChatServer() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_GetChatServer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetChatServer(::grpc::ServerContext* /*context*/, const ::chat_message::GetChatServerRequest* /*request*/, ::chat_message::GetChatServerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetChatServer(::grpc::ServerContext* context, ::chat_message::GetChatServerRequest* request, ::grpc::ServerAsyncResponseWriter< ::chat_message::GetChatServerResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Login() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Login(::grpc::ServerContext* /*context*/, const ::chat_message::LoginRequest* /*request*/, ::chat_message::LoginResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLogin(::grpc::ServerContext* context, ::chat_message::LoginRequest* request, ::grpc::ServerAsyncResponseWriter< ::chat_message::LoginResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_GetChatServer<WithAsyncMethod_Login<Service > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_GetChatServer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_GetChatServer() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::chat_message::GetChatServerRequest, ::chat_message::GetChatServerResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::chat_message::GetChatServerRequest* request, ::chat_message::GetChatServerResponse* response) { return this->GetChatServer(context, request, response); }));}
    void SetMessageAllocatorFor_GetChatServer(
        ::grpc::MessageAllocator< ::chat_message::GetChatServerRequest, ::chat_message::GetChatServerResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::chat_message::GetChatServerRequest, ::chat_message::GetChatServerResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_GetChatServer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetChatServer(::grpc::ServerContext* /*context*/, const ::chat_message::GetChatServerRequest* /*request*/, ::chat_message::GetChatServerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetChatServer(
      ::grpc::CallbackServerContext* /*context*/, const ::chat_message::GetChatServerRequest* /*request*/, ::chat_message::GetChatServerResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Login() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::chat_message::LoginRequest, ::chat_message::LoginResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::chat_message::LoginRequest* request, ::chat_message::LoginResponse* response) { return this->Login(context, request, response); }));}
    void SetMessageAllocatorFor_Login(
        ::grpc::MessageAllocator< ::chat_message::LoginRequest, ::chat_message::LoginResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::chat_message::LoginRequest, ::chat_message::LoginResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Login(::grpc::ServerContext* /*context*/, const ::chat_message::LoginRequest* /*request*/, ::chat_message::LoginResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Login(
      ::grpc::CallbackServerContext* /*context*/, const ::chat_message::LoginRequest* /*request*/, ::chat_message::LoginResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_GetChatServer<WithCallbackMethod_Login<Service > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_GetChatServer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_GetChatServer() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_GetChatServer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetChatServer(::grpc::ServerContext* /*context*/, const ::chat_message::GetChatServerRequest* /*request*/, ::chat_message::GetChatServerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Login() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Login(::grpc::ServerContext* /*context*/, const ::chat_message::LoginRequest* /*request*/, ::chat_message::LoginResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_GetChatServer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_GetChatServer() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_GetChatServer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetChatServer(::grpc::ServerContext* /*context*/, const ::chat_message::GetChatServerRequest* /*request*/, ::chat_message::GetChatServerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestGetChatServer(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Login() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Login(::grpc::ServerContext* /*context*/, const ::chat_message::LoginRequest* /*request*/, ::chat_message::LoginResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestLogin(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_GetChatServer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_GetChatServer() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->GetChatServer(context, request, response); }));
    }
    ~WithRawCallbackMethod_GetChatServer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status GetChatServer(::grpc::ServerContext* /*context*/, const ::chat_message::GetChatServerRequest* /*request*/, ::chat_message::GetChatServerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* GetChatServer(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Login() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->Login(context, request, response); }));
    }
    ~WithRawCallbackMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Login(::grpc::ServerContext* /*context*/, const ::chat_message::LoginRequest* /*request*/, ::chat_message::LoginResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* Login(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_GetChatServer : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_GetChatServer() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::chat_message::GetChatServerRequest, ::chat_message::GetChatServerResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::chat_message::GetChatServerRequest, ::chat_message::GetChatServerResponse>* streamer) {
                       return this->StreamedGetChatServer(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_GetChatServer() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status GetChatServer(::grpc::ServerContext* /*context*/, const ::chat_message::GetChatServerRequest* /*request*/, ::chat_message::GetChatServerResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedGetChatServer(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::chat_message::GetChatServerRequest,::chat_message::GetChatServerResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Login : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_Login() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::chat_message::LoginRequest, ::chat_message::LoginResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::chat_message::LoginRequest, ::chat_message::LoginResponse>* streamer) {
                       return this->StreamedLogin(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_Login() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Login(::grpc::ServerContext* /*context*/, const ::chat_message::LoginRequest* /*request*/, ::chat_message::LoginResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedLogin(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::chat_message::LoginRequest,::chat_message::LoginResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_GetChatServer<WithStreamedUnaryMethod_Login<Service > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_GetChatServer<WithStreamedUnaryMethod_Login<Service > > StreamedService;
};

class ChatService final {
 public:
  static constexpr char const* service_full_name() {
    return "chat_message.ChatService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status NotifyAddFriend(::grpc::ClientContext* context, const ::chat_message::AddFriendRequest& request, ::chat_message::AddFriendResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::AddFriendResponse>> AsyncNotifyAddFriend(::grpc::ClientContext* context, const ::chat_message::AddFriendRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::AddFriendResponse>>(AsyncNotifyAddFriendRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::AddFriendResponse>> PrepareAsyncNotifyAddFriend(::grpc::ClientContext* context, const ::chat_message::AddFriendRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::AddFriendResponse>>(PrepareAsyncNotifyAddFriendRaw(context, request, cq));
    }
    virtual ::grpc::Status NotifyAuthFriend(::grpc::ClientContext* context, const ::chat_message::AuthFriendRequest& request, ::chat_message::AuthFriendResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::AuthFriendResponse>> AsyncNotifyAuthFriend(::grpc::ClientContext* context, const ::chat_message::AuthFriendRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::AuthFriendResponse>>(AsyncNotifyAuthFriendRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::AuthFriendResponse>> PrepareAsyncNotifyAuthFriend(::grpc::ClientContext* context, const ::chat_message::AuthFriendRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::AuthFriendResponse>>(PrepareAsyncNotifyAuthFriendRaw(context, request, cq));
    }
    virtual ::grpc::Status NotifyTextChatTrans(::grpc::ClientContext* context, const ::chat_message::TextChatTransRequest& request, ::chat_message::TextChatTransResponse* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::TextChatTransResponse>> AsyncNotifyTextChatTrans(::grpc::ClientContext* context, const ::chat_message::TextChatTransRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::TextChatTransResponse>>(AsyncNotifyTextChatTransRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::TextChatTransResponse>> PrepareAsyncNotifyTextChatTrans(::grpc::ClientContext* context, const ::chat_message::TextChatTransRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::TextChatTransResponse>>(PrepareAsyncNotifyTextChatTransRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void NotifyAddFriend(::grpc::ClientContext* context, const ::chat_message::AddFriendRequest* request, ::chat_message::AddFriendResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void NotifyAddFriend(::grpc::ClientContext* context, const ::chat_message::AddFriendRequest* request, ::chat_message::AddFriendResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void NotifyAuthFriend(::grpc::ClientContext* context, const ::chat_message::AuthFriendRequest* request, ::chat_message::AuthFriendResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void NotifyAuthFriend(::grpc::ClientContext* context, const ::chat_message::AuthFriendRequest* request, ::chat_message::AuthFriendResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      virtual void NotifyTextChatTrans(::grpc::ClientContext* context, const ::chat_message::TextChatTransRequest* request, ::chat_message::TextChatTransResponse* response, std::function<void(::grpc::Status)>) = 0;
      virtual void NotifyTextChatTrans(::grpc::ClientContext* context, const ::chat_message::TextChatTransRequest* request, ::chat_message::TextChatTransResponse* response, ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::AddFriendResponse>* AsyncNotifyAddFriendRaw(::grpc::ClientContext* context, const ::chat_message::AddFriendRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::AddFriendResponse>* PrepareAsyncNotifyAddFriendRaw(::grpc::ClientContext* context, const ::chat_message::AddFriendRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::AuthFriendResponse>* AsyncNotifyAuthFriendRaw(::grpc::ClientContext* context, const ::chat_message::AuthFriendRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::AuthFriendResponse>* PrepareAsyncNotifyAuthFriendRaw(::grpc::ClientContext* context, const ::chat_message::AuthFriendRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::TextChatTransResponse>* AsyncNotifyTextChatTransRaw(::grpc::ClientContext* context, const ::chat_message::TextChatTransRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::chat_message::TextChatTransResponse>* PrepareAsyncNotifyTextChatTransRaw(::grpc::ClientContext* context, const ::chat_message::TextChatTransRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status NotifyAddFriend(::grpc::ClientContext* context, const ::chat_message::AddFriendRequest& request, ::chat_message::AddFriendResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat_message::AddFriendResponse>> AsyncNotifyAddFriend(::grpc::ClientContext* context, const ::chat_message::AddFriendRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat_message::AddFriendResponse>>(AsyncNotifyAddFriendRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat_message::AddFriendResponse>> PrepareAsyncNotifyAddFriend(::grpc::ClientContext* context, const ::chat_message::AddFriendRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat_message::AddFriendResponse>>(PrepareAsyncNotifyAddFriendRaw(context, request, cq));
    }
    ::grpc::Status NotifyAuthFriend(::grpc::ClientContext* context, const ::chat_message::AuthFriendRequest& request, ::chat_message::AuthFriendResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat_message::AuthFriendResponse>> AsyncNotifyAuthFriend(::grpc::ClientContext* context, const ::chat_message::AuthFriendRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat_message::AuthFriendResponse>>(AsyncNotifyAuthFriendRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat_message::AuthFriendResponse>> PrepareAsyncNotifyAuthFriend(::grpc::ClientContext* context, const ::chat_message::AuthFriendRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat_message::AuthFriendResponse>>(PrepareAsyncNotifyAuthFriendRaw(context, request, cq));
    }
    ::grpc::Status NotifyTextChatTrans(::grpc::ClientContext* context, const ::chat_message::TextChatTransRequest& request, ::chat_message::TextChatTransResponse* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat_message::TextChatTransResponse>> AsyncNotifyTextChatTrans(::grpc::ClientContext* context, const ::chat_message::TextChatTransRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat_message::TextChatTransResponse>>(AsyncNotifyTextChatTransRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat_message::TextChatTransResponse>> PrepareAsyncNotifyTextChatTrans(::grpc::ClientContext* context, const ::chat_message::TextChatTransRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::chat_message::TextChatTransResponse>>(PrepareAsyncNotifyTextChatTransRaw(context, request, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void NotifyAddFriend(::grpc::ClientContext* context, const ::chat_message::AddFriendRequest* request, ::chat_message::AddFriendResponse* response, std::function<void(::grpc::Status)>) override;
      void NotifyAddFriend(::grpc::ClientContext* context, const ::chat_message::AddFriendRequest* request, ::chat_message::AddFriendResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void NotifyAuthFriend(::grpc::ClientContext* context, const ::chat_message::AuthFriendRequest* request, ::chat_message::AuthFriendResponse* response, std::function<void(::grpc::Status)>) override;
      void NotifyAuthFriend(::grpc::ClientContext* context, const ::chat_message::AuthFriendRequest* request, ::chat_message::AuthFriendResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
      void NotifyTextChatTrans(::grpc::ClientContext* context, const ::chat_message::TextChatTransRequest* request, ::chat_message::TextChatTransResponse* response, std::function<void(::grpc::Status)>) override;
      void NotifyTextChatTrans(::grpc::ClientContext* context, const ::chat_message::TextChatTransRequest* request, ::chat_message::TextChatTransResponse* response, ::grpc::ClientUnaryReactor* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::chat_message::AddFriendResponse>* AsyncNotifyAddFriendRaw(::grpc::ClientContext* context, const ::chat_message::AddFriendRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chat_message::AddFriendResponse>* PrepareAsyncNotifyAddFriendRaw(::grpc::ClientContext* context, const ::chat_message::AddFriendRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chat_message::AuthFriendResponse>* AsyncNotifyAuthFriendRaw(::grpc::ClientContext* context, const ::chat_message::AuthFriendRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chat_message::AuthFriendResponse>* PrepareAsyncNotifyAuthFriendRaw(::grpc::ClientContext* context, const ::chat_message::AuthFriendRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chat_message::TextChatTransResponse>* AsyncNotifyTextChatTransRaw(::grpc::ClientContext* context, const ::chat_message::TextChatTransRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::chat_message::TextChatTransResponse>* PrepareAsyncNotifyTextChatTransRaw(::grpc::ClientContext* context, const ::chat_message::TextChatTransRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_NotifyAddFriend_;
    const ::grpc::internal::RpcMethod rpcmethod_NotifyAuthFriend_;
    const ::grpc::internal::RpcMethod rpcmethod_NotifyTextChatTrans_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status NotifyAddFriend(::grpc::ServerContext* context, const ::chat_message::AddFriendRequest* request, ::chat_message::AddFriendResponse* response);
    virtual ::grpc::Status NotifyAuthFriend(::grpc::ServerContext* context, const ::chat_message::AuthFriendRequest* request, ::chat_message::AuthFriendResponse* response);
    virtual ::grpc::Status NotifyTextChatTrans(::grpc::ServerContext* context, const ::chat_message::TextChatTransRequest* request, ::chat_message::TextChatTransResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_NotifyAddFriend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_NotifyAddFriend() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_NotifyAddFriend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NotifyAddFriend(::grpc::ServerContext* /*context*/, const ::chat_message::AddFriendRequest* /*request*/, ::chat_message::AddFriendResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestNotifyAddFriend(::grpc::ServerContext* context, ::chat_message::AddFriendRequest* request, ::grpc::ServerAsyncResponseWriter< ::chat_message::AddFriendResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_NotifyAuthFriend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_NotifyAuthFriend() {
      ::grpc::Service::MarkMethodAsync(1);
    }
    ~WithAsyncMethod_NotifyAuthFriend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NotifyAuthFriend(::grpc::ServerContext* /*context*/, const ::chat_message::AuthFriendRequest* /*request*/, ::chat_message::AuthFriendResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestNotifyAuthFriend(::grpc::ServerContext* context, ::chat_message::AuthFriendRequest* request, ::grpc::ServerAsyncResponseWriter< ::chat_message::AuthFriendResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithAsyncMethod_NotifyTextChatTrans : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_NotifyTextChatTrans() {
      ::grpc::Service::MarkMethodAsync(2);
    }
    ~WithAsyncMethod_NotifyTextChatTrans() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NotifyTextChatTrans(::grpc::ServerContext* /*context*/, const ::chat_message::TextChatTransRequest* /*request*/, ::chat_message::TextChatTransResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestNotifyTextChatTrans(::grpc::ServerContext* context, ::chat_message::TextChatTransRequest* request, ::grpc::ServerAsyncResponseWriter< ::chat_message::TextChatTransResponse>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_NotifyAddFriend<WithAsyncMethod_NotifyAuthFriend<WithAsyncMethod_NotifyTextChatTrans<Service > > > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_NotifyAddFriend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_NotifyAddFriend() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::chat_message::AddFriendRequest, ::chat_message::AddFriendResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::chat_message::AddFriendRequest* request, ::chat_message::AddFriendResponse* response) { return this->NotifyAddFriend(context, request, response); }));}
    void SetMessageAllocatorFor_NotifyAddFriend(
        ::grpc::MessageAllocator< ::chat_message::AddFriendRequest, ::chat_message::AddFriendResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::chat_message::AddFriendRequest, ::chat_message::AddFriendResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_NotifyAddFriend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NotifyAddFriend(::grpc::ServerContext* /*context*/, const ::chat_message::AddFriendRequest* /*request*/, ::chat_message::AddFriendResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* NotifyAddFriend(
      ::grpc::CallbackServerContext* /*context*/, const ::chat_message::AddFriendRequest* /*request*/, ::chat_message::AddFriendResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_NotifyAuthFriend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_NotifyAuthFriend() {
      ::grpc::Service::MarkMethodCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::chat_message::AuthFriendRequest, ::chat_message::AuthFriendResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::chat_message::AuthFriendRequest* request, ::chat_message::AuthFriendResponse* response) { return this->NotifyAuthFriend(context, request, response); }));}
    void SetMessageAllocatorFor_NotifyAuthFriend(
        ::grpc::MessageAllocator< ::chat_message::AuthFriendRequest, ::chat_message::AuthFriendResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(1);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::chat_message::AuthFriendRequest, ::chat_message::AuthFriendResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_NotifyAuthFriend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NotifyAuthFriend(::grpc::ServerContext* /*context*/, const ::chat_message::AuthFriendRequest* /*request*/, ::chat_message::AuthFriendResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* NotifyAuthFriend(
      ::grpc::CallbackServerContext* /*context*/, const ::chat_message::AuthFriendRequest* /*request*/, ::chat_message::AuthFriendResponse* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithCallbackMethod_NotifyTextChatTrans : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_NotifyTextChatTrans() {
      ::grpc::Service::MarkMethodCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::chat_message::TextChatTransRequest, ::chat_message::TextChatTransResponse>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::chat_message::TextChatTransRequest* request, ::chat_message::TextChatTransResponse* response) { return this->NotifyTextChatTrans(context, request, response); }));}
    void SetMessageAllocatorFor_NotifyTextChatTrans(
        ::grpc::MessageAllocator< ::chat_message::TextChatTransRequest, ::chat_message::TextChatTransResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(2);
      static_cast<::grpc::internal::CallbackUnaryHandler< ::chat_message::TextChatTransRequest, ::chat_message::TextChatTransResponse>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_NotifyTextChatTrans() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NotifyTextChatTrans(::grpc::ServerContext* /*context*/, const ::chat_message::TextChatTransRequest* /*request*/, ::chat_message::TextChatTransResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* NotifyTextChatTrans(
      ::grpc::CallbackServerContext* /*context*/, const ::chat_message::TextChatTransRequest* /*request*/, ::chat_message::TextChatTransResponse* /*response*/)  { return nullptr; }
  };
  typedef WithCallbackMethod_NotifyAddFriend<WithCallbackMethod_NotifyAuthFriend<WithCallbackMethod_NotifyTextChatTrans<Service > > > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_NotifyAddFriend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_NotifyAddFriend() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_NotifyAddFriend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NotifyAddFriend(::grpc::ServerContext* /*context*/, const ::chat_message::AddFriendRequest* /*request*/, ::chat_message::AddFriendResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_NotifyAuthFriend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_NotifyAuthFriend() {
      ::grpc::Service::MarkMethodGeneric(1);
    }
    ~WithGenericMethod_NotifyAuthFriend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NotifyAuthFriend(::grpc::ServerContext* /*context*/, const ::chat_message::AuthFriendRequest* /*request*/, ::chat_message::AuthFriendResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithGenericMethod_NotifyTextChatTrans : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_NotifyTextChatTrans() {
      ::grpc::Service::MarkMethodGeneric(2);
    }
    ~WithGenericMethod_NotifyTextChatTrans() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NotifyTextChatTrans(::grpc::ServerContext* /*context*/, const ::chat_message::TextChatTransRequest* /*request*/, ::chat_message::TextChatTransResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_NotifyAddFriend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_NotifyAddFriend() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_NotifyAddFriend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NotifyAddFriend(::grpc::ServerContext* /*context*/, const ::chat_message::AddFriendRequest* /*request*/, ::chat_message::AddFriendResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestNotifyAddFriend(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_NotifyAuthFriend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_NotifyAuthFriend() {
      ::grpc::Service::MarkMethodRaw(1);
    }
    ~WithRawMethod_NotifyAuthFriend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NotifyAuthFriend(::grpc::ServerContext* /*context*/, const ::chat_message::AuthFriendRequest* /*request*/, ::chat_message::AuthFriendResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestNotifyAuthFriend(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(1, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawMethod_NotifyTextChatTrans : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_NotifyTextChatTrans() {
      ::grpc::Service::MarkMethodRaw(2);
    }
    ~WithRawMethod_NotifyTextChatTrans() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NotifyTextChatTrans(::grpc::ServerContext* /*context*/, const ::chat_message::TextChatTransRequest* /*request*/, ::chat_message::TextChatTransResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestNotifyTextChatTrans(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(2, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_NotifyAddFriend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_NotifyAddFriend() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->NotifyAddFriend(context, request, response); }));
    }
    ~WithRawCallbackMethod_NotifyAddFriend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NotifyAddFriend(::grpc::ServerContext* /*context*/, const ::chat_message::AddFriendRequest* /*request*/, ::chat_message::AddFriendResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* NotifyAddFriend(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_NotifyAuthFriend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_NotifyAuthFriend() {
      ::grpc::Service::MarkMethodRawCallback(1,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->NotifyAuthFriend(context, request, response); }));
    }
    ~WithRawCallbackMethod_NotifyAuthFriend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NotifyAuthFriend(::grpc::ServerContext* /*context*/, const ::chat_message::AuthFriendRequest* /*request*/, ::chat_message::AuthFriendResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* NotifyAuthFriend(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_NotifyTextChatTrans : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_NotifyTextChatTrans() {
      ::grpc::Service::MarkMethodRawCallback(2,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->NotifyTextChatTrans(context, request, response); }));
    }
    ~WithRawCallbackMethod_NotifyTextChatTrans() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status NotifyTextChatTrans(::grpc::ServerContext* /*context*/, const ::chat_message::TextChatTransRequest* /*request*/, ::chat_message::TextChatTransResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* NotifyTextChatTrans(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)  { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_NotifyAddFriend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_NotifyAddFriend() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::chat_message::AddFriendRequest, ::chat_message::AddFriendResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::chat_message::AddFriendRequest, ::chat_message::AddFriendResponse>* streamer) {
                       return this->StreamedNotifyAddFriend(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_NotifyAddFriend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status NotifyAddFriend(::grpc::ServerContext* /*context*/, const ::chat_message::AddFriendRequest* /*request*/, ::chat_message::AddFriendResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedNotifyAddFriend(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::chat_message::AddFriendRequest,::chat_message::AddFriendResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_NotifyAuthFriend : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_NotifyAuthFriend() {
      ::grpc::Service::MarkMethodStreamed(1,
        new ::grpc::internal::StreamedUnaryHandler<
          ::chat_message::AuthFriendRequest, ::chat_message::AuthFriendResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::chat_message::AuthFriendRequest, ::chat_message::AuthFriendResponse>* streamer) {
                       return this->StreamedNotifyAuthFriend(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_NotifyAuthFriend() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status NotifyAuthFriend(::grpc::ServerContext* /*context*/, const ::chat_message::AuthFriendRequest* /*request*/, ::chat_message::AuthFriendResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedNotifyAuthFriend(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::chat_message::AuthFriendRequest,::chat_message::AuthFriendResponse>* server_unary_streamer) = 0;
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_NotifyTextChatTrans : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_NotifyTextChatTrans() {
      ::grpc::Service::MarkMethodStreamed(2,
        new ::grpc::internal::StreamedUnaryHandler<
          ::chat_message::TextChatTransRequest, ::chat_message::TextChatTransResponse>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::chat_message::TextChatTransRequest, ::chat_message::TextChatTransResponse>* streamer) {
                       return this->StreamedNotifyTextChatTrans(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_NotifyTextChatTrans() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status NotifyTextChatTrans(::grpc::ServerContext* /*context*/, const ::chat_message::TextChatTransRequest* /*request*/, ::chat_message::TextChatTransResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedNotifyTextChatTrans(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::chat_message::TextChatTransRequest,::chat_message::TextChatTransResponse>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_NotifyAddFriend<WithStreamedUnaryMethod_NotifyAuthFriend<WithStreamedUnaryMethod_NotifyTextChatTrans<Service > > > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_NotifyAddFriend<WithStreamedUnaryMethod_NotifyAuthFriend<WithStreamedUnaryMethod_NotifyTextChatTrans<Service > > > StreamedService;
};

}  // namespace chat_message


#endif  // GRPC_message_2eproto__INCLUDED
